export default {
    WB_AUTH_TOKEN: 'Workbook-Auth-Token',
    AUTH_HEADER_NAME: 'X-Auth-Token',
    DEFAULT_USER: {
        _id: '',
        token: '',
        firstName: 'John',
        lastName: 'Doe',
        address: 'None',
        email: 'john.doe@gmail.com',
        role: 'user',
        location: {
            city: '',
            coordinates: [0, 0],
            country: '',
            formattedAddress: '',
            state: '',
            street: '',
            type: '',
            zipcode: '',
        },
    },
    MAX_OFFER_IMGS: 4,
    MAX_FILE_SIZE: 1000000,
};
